[package]
name = "adtep"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.1"
panic-halt = "0.2"
ufmt = "0.2"

[dependencies.arduino-hal]
git = "https://github.com/Rahix/avr-hal.git"
features = ["arduino-uno", "critical-section-impl"]
