[unstable]
build-std = ["core"]
build-std-features = ["optimize_for_size", "panic_immediate_abort"]

[build]
target = "avr-atmega328p.json"

[target.avr-atmega328p]
runner = "ravedude -c -b 115200 uno"

[env]
AVR_CPU_FREQUENCY_HZ = "16_000_000"

[profile.release]
opt-level = "z"
codegen-units = 1
panic = "abort"
strip = true
lto = true
